project_name: dagger

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/dagger
    binary: dagger
    ldflags:
      - -s -w
      - -X github.com/dagger/dagger/internal/engine.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
