version: "3.8"

services:
  buildkitd:
    container_name: dagger-buildkitd-jaeger
    image: moby/buildkit:latest
    command: "--debug"
    privileged: true
    environment:
      - JAEGER_TRACE=jaeger:6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.33.0
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - type: bind
        source: ./jaeger
        target: /badger
