// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Gcexp struct { // gcexp (../../../../../:0:0)
	query *querybuilder.Selection

	chain       *string
	cutoff      *string
	dirScale    *string
	fanout      *string
	goChain     *string
	id          *ID
	layered     *string
	lazyCutoff  *string
	mountScale  *string
	packTool    *string
	plain       *string
	plainStd    *string
	planCheck   *string
	planDebug   *string
	planScripts *string
	replay      *string
}

func (r *Gcexp) WithGraphQLQuery(q *querybuilder.Selection) *Gcexp {
	return &Gcexp{
		query: q,
	}
}

// Chain runs n execs in sequence; each one mounts the previous output file.
// Only the final file is read, so the engine sees one dependent chain.
func (r *Gcexp) Chain(ctx context.Context, n int, salt string, nonce string) (string, error) {
	if r.chain != nil {
		return *r.chain, nil
	}
	q := r.query.Select("chain")
	q = q.Arg("n", n)
	q = q.Arg("salt", salt)
	q = q.Arg("nonce", nonce)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Cutoff checks whether a consumer exec is reused when its input file comes
// from a different producer recipe that wrote identical bytes.
func (r *Gcexp) Cutoff(ctx context.Context, salt string) (string, error) {
	if r.cutoff != nil {
		return *r.cutoff, nil
	}
	q := r.query.Select("cutoff")
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DirScale gathers n distinct files with one withFiles call and mounts the
// resulting directory once.
func (r *Gcexp) DirScale(ctx context.Context, n int, salt string, nonce string) (string, error) {
	if r.dirScale != nil {
		return *r.dirScale, nil
	}
	q := r.query.Select("dirScale")
	q = q.Arg("n", n)
	q = q.Arg("salt", salt)
	q = q.Arg("nonce", nonce)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Fanout runs n independent execs in parallel and reads each output file.
// It reports the wall time inside the function.
func (r *Gcexp) Fanout(ctx context.Context, n int, salt string, nonce string) (string, error) {
	if r.fanout != nil {
		return *r.fanout, nil
	}
	q := r.query.Select("fanout")
	q = q.Arg("n", n)
	q = q.Arg("salt", salt)
	q = q.Arg("nonce", nonce)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GoChain is Chain on the golang image instead of alpine.
func (r *Gcexp) GoChain(ctx context.Context, n int, salt string, nonce string) (string, error) {
	if r.goChain != nil {
		return *r.goChain, nil
	}
	q := r.query.Select("goChain")
	q = q.Arg("n", n)
	q = q.Arg("salt", salt)
	q = q.Arg("nonce", nonce)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Gcexp.
func (r *Gcexp) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Gcexp) XXX_GraphQLType() string {
	return "Gcexp"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Gcexp) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Gcexp) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Gcexp) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Gcexp) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Gcexp{query: selectNode(dag.query, id, "Gcexp")}
	return nil
}

// Layered builds in three steps with no engine changes:
//  1. list the non-main-module packages the build needs (reruns on any source change, cheap);
//  2. build those packages into a GOCACHE directory output, keyed on that list's
//     content plus go.mod/go.sum (a normal cached result, not a cache volume);
//  3. go build with GOCACHE seeded from step 2 (copy-on-write mount).
func (r *Gcexp) Layered(ctx context.Context, src *Directory, nonce string, salt string) (string, error) {
	assertNotNil("src", src)
	if r.layered != nil {
		return *r.layered, nil
	}
	q := r.query.Select("layered")
	q = q.Arg("src", src)
	q = q.Arg("nonce", nonce)
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// LazyCutoff checks early cutoff when nothing is synced between producer and
// consumer. Each case builds a consumer over a file from a producer recipe
// that differs from the reference's but writes identical bytes, and reports
// whether the consumer's exec was reused.
func (r *Gcexp) LazyCutoff(ctx context.Context, salt string) (string, error) {
	if r.lazyCutoff != nil {
		return *r.lazyCutoff, nil
	}
	q := r.query.Select("lazyCutoff")
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// MountScale runs one exec with n mounted files, each a distinct small file.
func (r *Gcexp) MountScale(ctx context.Context, n int, salt string, nonce string) (string, error) {
	if r.mountScale != nil {
		return *r.mountScale, nil
	}
	q := r.query.Select("mountScale")
	q = q.Arg("n", n)
	q = q.Arg("salt", salt)
	q = q.Arg("nonce", nonce)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PackTool builds the pack tool and the header tool and reports their sizes.
// They are built once per engine and cached; harnesses call it before
// measuring so a measured first build excludes them.
func (r *Gcexp) PackTool(ctx context.Context) (string, error) {
	if r.packTool != nil {
		return *r.packTool, nil
	}
	q := r.query.Select("packTool")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Plain builds the same package with one go build exec. With a non-empty
// volume name, GOCACHE lives in that cache volume.
func (r *Gcexp) Plain(ctx context.Context, src *Directory, nonce string, volume string, salt string) (string, error) {
	assertNotNil("src", src)
	if r.plain != nil {
		return *r.plain, nil
	}
	q := r.query.Select("plain")
	q = q.Arg("src", src)
	q = q.Arg("nonce", nonce)
	q = q.Arg("volume", volume)
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PlainStd builds the standard library into a GOCACHE volume, as a previous
// build with the same toolchain would have, so a later Plain with that volume
// starts with a warm standard library.
func (r *Gcexp) PlainStd(ctx context.Context, volume string, salt string) (string, error) {
	if r.plainStd != nil {
		return *r.plainStd, nil
	}
	q := r.query.Select("plainStd")
	q = q.Arg("volume", volume)
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PlanCheck compares the plan made from the whole source with the plan made
// from its header pack, ignoring build IDs. It is the hdr mode's correctness
// check: the two must render the same per-package scripts.
func (r *Gcexp) PlanCheck(ctx context.Context, src *Directory) (string, error) {
	assertNotNil("src", src)
	if r.planCheck != nil {
		return *r.planCheck, nil
	}
	q := r.query.Select("planCheck")
	q = q.Arg("src", src)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PlanDebug shows how one package's block was parsed.
func (r *Gcexp) PlanDebug(ctx context.Context, src *Directory, importPath string) (string, error) {
	assertNotNil("src", src)
	if r.planDebug != nil {
		return *r.planDebug, nil
	}
	q := r.query.Select("planDebug")
	q = q.Arg("src", src)
	q = q.Arg("importPath", importPath)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PlanScripts lists, per package in src's plan, its import path and a digest
// of everything its exec depends on apart from its dependencies' outputs: the
// rendered script and its source file lists. Two projects whose lines match
// for a package build it with the same exec, given the same dependency
// outputs and source contents.
func (r *Gcexp) PlanScripts(ctx context.Context, src *Directory) (string, error) {
	assertNotNil("src", src)
	if r.planScripts != nil {
		return *r.planScripts, nil
	}
	q := r.query.Select("planScripts")
	q = q.Arg("src", src)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GcexpReplayOpts contains options for Gcexp.Replay
type GcexpReplayOpts struct {

	// Default: 32
	Concurrency int
	// Write and read a per-package stamp that changes only when that
	// package's exec ran. Off, the replay does only what a real build does;
	// verify re-runs from exec counts instead.
	//
	// Default: true
	Stamps bool
	// g23 prototype modes, comma-separated: memo, coarse, lazy, hdr (see
	// modeOpts). Empty runs driver v1 unchanged.
	Mode string
}

// Replay builds the main package at the root of src with one exec per package.
// It returns the wall time and, per package, a stamp that changes only when
// that package's exec actually ran.
func (r *Gcexp) Replay(ctx context.Context, src *Directory, nonce string, salt string, opts ...GcexpReplayOpts) (string, error) {
	assertNotNil("src", src)
	if r.replay != nil {
		return *r.replay, nil
	}
	q := r.query.Select("replay")
	for i := len(opts) - 1; i >= 0; i-- {
		// `concurrency` optional argument
		if !querybuilder.IsZeroValue(opts[i].Concurrency) {
			q = q.Arg("concurrency", opts[i].Concurrency)
		}
		// `stamps` optional argument
		if !querybuilder.IsZeroValue(opts[i].Stamps) {
			q = q.Arg("stamps", opts[i].Stamps)
		}
		// `mode` optional argument
		if !querybuilder.IsZeroValue(opts[i].Mode) {
			q = q.Arg("mode", opts[i].Mode)
		}
	}
	q = q.Arg("src", src)
	q = q.Arg("nonce", nonce)
	q = q.Arg("salt", salt)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GcexpTierOpts contains options for Gcexp.Tier
type GcexpTierOpts struct {

	// Default: 16
	Concurrency int
	// Build the tier in one exec under make -j instead of one exec per package.
	Coarse bool
}

// Tier builds the packages in spec (the standard library and dependency
// modules of a build) and returns a directory with one archive per package,
// named <name>.a. It is a module function, so the whole tier is one cached
// call: unchanged, a build pays one cache hit for it instead of walking it.
func (r *Gcexp) Tier(spec string, mods *Directory, salt string, opts ...GcexpTierOpts) *Directory {
	assertNotNil("mods", mods)
	q := r.query.Select("tier")
	for i := len(opts) - 1; i >= 0; i-- {
		// `concurrency` optional argument
		if !querybuilder.IsZeroValue(opts[i].Concurrency) {
			q = q.Arg("concurrency", opts[i].Concurrency)
		}
		// `coarse` optional argument
		if !querybuilder.IsZeroValue(opts[i].Coarse) {
			q = q.Arg("coarse", opts[i].Coarse)
		}
	}
	q = q.Arg("spec", spec)
	q = q.Arg("mods", mods)
	q = q.Arg("salt", salt)

	return &Directory{
		query: q,
	}
}

func (r *Query) Gcexp() *Gcexp { // gcexp (../../../../../:0:0)
	q := r.query.Select("gcexp")

	return &Gcexp{
		query: q,
	}
}
