// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/gcexp/internal/dagger/core"
)

type Gcexp = core.Gcexp

// GcexpPlainOpts contains options for Gcexp.Plain
type GcexpPlainOpts = core.GcexpPlainOpts

// GcexpPlanCheckOpts contains options for Gcexp.PlanCheck
type GcexpPlanCheckOpts = core.GcexpPlanCheckOpts

// GcexpPlanDebugOpts contains options for Gcexp.PlanDebug
type GcexpPlanDebugOpts = core.GcexpPlanDebugOpts

// GcexpPlanScriptsOpts contains options for Gcexp.PlanScripts
type GcexpPlanScriptsOpts = core.GcexpPlanScriptsOpts

// GcexpReplayOpts contains options for Gcexp.Replay
type GcexpReplayOpts = core.GcexpReplayOpts

// GcexpTierOpts contains options for Gcexp.Tier
type GcexpTierOpts = core.GcexpTierOpts
