// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/gcexp/internal/dagger/core"
)

type Gcexp = core.Gcexp

// GcexpPlainOpts contains options for Gcexp.Plain
type GcexpPlainOpts = core.GcexpPlainOpts

// GcexpReplayOpts contains options for Gcexp.Replay
type GcexpReplayOpts = core.GcexpReplayOpts
