// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type NamespaceDemo struct { // namespace-demo (../../../../../:0:0)
	query *querybuilder.Selection

	baseImageAddress *string
	build            *Void
	buildCli         *Void
	id               *ID
}

func (r *NamespaceDemo) WithGraphQLQuery(q *querybuilder.Selection) *NamespaceDemo {
	return &NamespaceDemo{
		query: q,
	}
}

// Compile cmd/dnsname into an initially empty /out mount and return it.
func (r *NamespaceDemo) Artifact() *Directory {
	q := r.query.Select("artifact")

	return &Directory{
		query: q,
	}
}

// Image the build runs on.
func (r *NamespaceDemo) BaseImageAddress(ctx context.Context) (string, error) {
	if r.baseImageAddress != nil {
		return *r.baseImageAddress, nil
	}
	q := r.query.Select("baseImageAddress")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Build the artifact and verify it is there.
func (r *NamespaceDemo) Build(ctx context.Context) error {
	if r.build != nil {
		return nil
	}
	q := r.query.Select("build")

	return q.Execute(ctx)
}

// Build the dagger CLI for linux/amd64 and verify the binary is there.
func (r *NamespaceDemo) BuildCli(ctx context.Context) error {
	if r.buildCli != nil {
		return nil
	}
	q := r.query.Select("buildCli")

	return q.Execute(ctx)
}

// Build the dagger CLI for linux/amd64 with the cli module and write it into
// an initially empty /out mount.
func (r *NamespaceDemo) CliArtifact() *Directory {
	q := r.query.Select("cliArtifact")

	return &Directory{
		query: q,
	}
}

// A container with the source mounted, ready to build on.
func (r *NamespaceDemo) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this NamespaceDemo.
func (r *NamespaceDemo) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *NamespaceDemo) XXX_GraphQLType() string {
	return "NamespaceDemo"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *NamespaceDemo) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *NamespaceDemo) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *NamespaceDemo) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *NamespaceDemo) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = NamespaceDemo{query: selectNode(dag.query, id, "NamespaceDemo")}
	return nil
}

// NamespaceDemoOpts contains options for Query.NamespaceDemo
type NamespaceDemoOpts struct {

	// Default: "golang:1.26-alpine"
	BaseImageAddress string
}

func (r *Query) NamespaceDemo(ws *Workspace, opts ...NamespaceDemoOpts) *NamespaceDemo { // namespace-demo (../../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("namespaceDemo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `baseImageAddress` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseImageAddress) {
			q = q.Arg("baseImageAddress", opts[i].BaseImageAddress)
		}
	}
	q = q.Arg("ws", ws)

	return &NamespaceDemo{
		query: q,
	}
}
