// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/gcexp/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Gcexp) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Gcexp) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Gcexp":
		switch fnName {
		case "Chain":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			return (*Gcexp).Chain(&parent, ctx, n, salt, nonce)
		case "Cutoff":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			return (*Gcexp).Cutoff(&parent, ctx, salt)
		case "DirScale":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			return (*Gcexp).DirScale(&parent, ctx, n, salt, nonce)
		case "Fanout":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			return (*Gcexp).Fanout(&parent, ctx, n, salt, nonce)
		case "GoChain":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			return (*Gcexp).GoChain(&parent, ctx, n, salt, nonce)
		case "Layered":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var src *dagger.Directory
			if inputArgs["src"] != nil {
				err = json.Unmarshal([]byte(inputArgs["src"]), &src)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg src", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			return (*Gcexp).Layered(&parent, ctx, src, nonce, salt)
		case "MountScale":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			return (*Gcexp).MountScale(&parent, ctx, n, salt, nonce)
		case "PackTool":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Gcexp).PackTool(&parent, ctx)
		case "Plain":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var src *dagger.Directory
			if inputArgs["src"] != nil {
				err = json.Unmarshal([]byte(inputArgs["src"]), &src)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg src", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			var volume string
			if inputArgs["volume"] != nil {
				err = json.Unmarshal([]byte(inputArgs["volume"]), &volume)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg volume", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			return (*Gcexp).Plain(&parent, ctx, src, nonce, volume, salt)
		case "PlanDebug":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var src *dagger.Directory
			if inputArgs["src"] != nil {
				err = json.Unmarshal([]byte(inputArgs["src"]), &src)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg src", err))
				}
			}
			var importPath string
			if inputArgs["importPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["importPath"]), &importPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg importPath", err))
				}
			}
			return (*Gcexp).PlanDebug(&parent, ctx, src, importPath)
		case "Replay":
			var parent Gcexp
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var src *dagger.Directory
			if inputArgs["src"] != nil {
				err = json.Unmarshal([]byte(inputArgs["src"]), &src)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg src", err))
				}
			}
			var nonce string
			if inputArgs["nonce"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nonce"]), &nonce)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nonce", err))
				}
			}
			var salt string
			if inputArgs["salt"] != nil {
				err = json.Unmarshal([]byte(inputArgs["salt"]), &salt)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg salt", err))
				}
			}
			var concurrency int
			if inputArgs["concurrency"] != nil {
				err = json.Unmarshal([]byte(inputArgs["concurrency"]), &concurrency)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg concurrency", err))
				}
			}
			var stamps bool
			if inputArgs["stamps"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stamps"]), &stamps)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stamps", err))
				}
			}
			var knobs string
			if inputArgs["knobs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knobs"]), &knobs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knobs", err))
				}
			}
			return (*Gcexp).Replay(&parent, ctx, src, nonce, salt, concurrency, stamps, knobs)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("Experiments for the fine-grained Go build caching research.\n").
			WithObject(
				dag.TypeDef().WithObject("Gcexp", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 14, 6)}).
					WithFunction(
						dag.Function("Chain",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Chain runs n execs in sequence; each one mounts the previous output file.\nOnly the final file is read, so the engine sees one dependent chain.").
							WithSourceMap(dag.SourceMap("main.go", 46, 1)).
							WithArg("n", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 46, 44)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 46, 51)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 46, 64)})).
					WithFunction(
						dag.Function("Cutoff",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Cutoff checks whether a consumer exec is reused when its input file comes\nfrom a different producer recipe that wrote identical bytes.").
							WithSourceMap(dag.SourceMap("main.go", 63, 1)).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 63, 45)})).
					WithFunction(
						dag.Function("DirScale",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("DirScale gathers n distinct files with one withFiles call and mounts the\nresulting directory once.").
							WithSourceMap(dag.SourceMap("main.go", 151, 1)).
							WithArg("n", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 151, 47)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 151, 54)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 151, 67)})).
					WithFunction(
						dag.Function("Fanout",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Fanout runs n independent execs in parallel and reads each output file.\nIt reports the wall time inside the function.").
							WithSourceMap(dag.SourceMap("main.go", 22, 1)).
							WithArg("n", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 22, 45)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 22, 52)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 22, 65)})).
					WithFunction(
						dag.Function("GoChain",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("GoChain is Chain on the golang image instead of alpine.").
							WithSourceMap(dag.SourceMap("main.go", 134, 1)).
							WithArg("n", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 134, 46)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 134, 53)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 134, 66)})).
					WithFunction(
						dag.Function("Layered",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Layered builds in three steps with no engine changes:\n 1. list the non-main-module packages the build needs (reruns on any source change, cheap);\n 2. build those packages into a GOCACHE directory output, keyed on that list's\n    content plus go.mod/go.sum (a normal cached result, not a cache volume);\n 3. go build with GOCACHE seeded from step 2 (copy-on-write mount).").
							WithSourceMap(dag.SourceMap("replay.go", 570, 1)).
							WithArg("src", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 570, 46)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 570, 69)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 570, 83)})).
					WithFunction(
						dag.Function("MountScale",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("MountScale runs one exec with n mounted files, each a distinct small file.").
							WithSourceMap(dag.SourceMap("main.go", 119, 1)).
							WithArg("n", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 119, 49)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 119, 56)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 119, 69)})).
					WithFunction(
						dag.Function("PackTool",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("PackTool builds the pack tool and reports its size. It is built once per\nengine and cached; harnesses call it before measuring so a measured first\nbuild excludes it.").
							WithSourceMap(dag.SourceMap("replay.go", 263, 1))).
					WithFunction(
						dag.Function("Plain",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Plain builds the same package with one go build exec. With a non-empty\nvolume name, GOCACHE lives in that cache volume.").
							WithSourceMap(dag.SourceMap("replay.go", 514, 1)).
							WithArg("src", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 514, 44)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 514, 67)}).
							WithArg("volume", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 514, 81)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 514, 96)})).
					WithFunction(
						dag.Function("PlanDebug",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("PlanDebug shows how one package's block was parsed.").
							WithSourceMap(dag.SourceMap("replay.go", 538, 1)).
							WithArg("src", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 538, 48)}).
							WithArg("importPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 538, 71)})).
					WithFunction(
						dag.Function("Replay",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Replay builds the main package at the root of src with one exec per package.\nIt returns the wall time and, per package, a stamp that changes only when\nthat package's exec actually ran.").
							WithSourceMap(dag.SourceMap("replay.go", 274, 1)).
							WithArg("src", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 274, 45)}).
							WithArg("nonce", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 274, 68)}).
							WithArg("salt", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 274, 82)}).
							WithArg("concurrency", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("replay.go", 276, 2), DefaultValue: dagger.JSON("32")}).
							WithArg("stamps", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind), dagger.FunctionWithArgOpts{Description: "Write and read a per-package stamp that changes only when that\npackage's exec ran. Off, the replay does only what a real build does;\nverify re-runs from exec counts instead.", SourceMap: dag.SourceMap("replay.go", 281, 2), DefaultValue: dagger.JSON("true")}).
							WithArg("knobs", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Comma-separated driver options to measure (prototype): \"ro\" mounts each\npackage's inputs read-only; \"pack\" mounts the pack tool only where the\npackage uses it; \"slot\" frees the concurrency slot when the exec is\ndone; \"overlap\" builds the base container while planning; \"redirect\"\nruns the plan exec without a shell; \"noinit\" runs package execs\nwithout the injected init. Empty runs the first prototype unchanged.\n\"merge\" puts dependency archives inside the package's source mount.", SourceMap: dag.SourceMap("replay.go", 290, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
