package main

import "os"

func main() {
	const contents = `package gomodulegenerate

const GeneratedValue = "generated by go generate"
`
	if err := os.WriteFile("generated.go", []byte(contents), 0o644); err != nil {
		panic(err)
	}
}
