name: test-runner
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: dagger-runner
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "dagger/dagger"
          ref: "v0.3.7"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: cd sdk/go && go test -v ./...
